---
title: "Learn more"
---

Want to learn more about different plants, insects, wildlife, or transitioning your yard? Check out the many links below! I could reinvent the wheel and write about all of this myself, but these people and groups below have already done a great job of writing about these topics. Please visit their sites and explore the knowledge:

## Reasons to transform your yard:

 - [Carbon Sponges](https://www.audubon.org/news/plant-trees-turn-your-yard-bird-oasis-and-carbon-sponge){target="_blank"}
 - [Prevent wildlife food deserts](https://www.audubon.org/news/yards-non-native-plants-create-food-deserts-bugs-and-birds){target="_blank"}
 - [Climate friendly makeovers](https://www.audubon.org/news/your-yard-stealthy-fossil-fuel-guzzler-give-it-climate-makeover){target="_blank"}
 - [Downside to green lawns](https://www.smithsonianmag.com/science-nature/another-downside-to-your-classic-green-lawn-22716743/){target="_blank"}
 - [Change the lawn](https://permaculturenews.org/2016/06/03/why-our-lawns-are-bad-for-the-environment-and-how-to-change-them-for-the-better/){target="_blank"}
 
## Information about using Florida native plants:

 - [Florida Native Plant Society](https://www.fnps.org/natives/natives){target="_blank"}
 - [Plant Real Florida](https://www.plantrealflorida.org/){target="_blank"}
 - [Florida native nurseries](https://www.floridanativenurseries.org/plants/){target="_blank"}
 - [UF IFAS](http://gardeningsolutions.ifas.ufl.edu/plants/ornamentals/native-plants.html){target="_blank"}
 - [Florida Yards](http://floridayards.org/fyplants/){target="_blank"}
 
## Gardening for insects:

 - [Pollinators Plans](https://xerces.org/pollinator-conservation/plant-lists/pollinator-plants-florida/){target="_blank"}
 - [Bees](https://flawildflowers.org/attracting-bees/){target="_blank"}
 - [Gardening for insects](https://www.amentsoc.org/insects/insects-and-man/gardening-for-insects.html){target="_blank"}

## Florida native bees:
 - [Florida Native Bees](https://conference.ifas.ufl.edu/gardener12/Onsite%20Presentations/Monday/0345%20Concurrent%20Session%203/D-3/0345%20M%20Peterson.pdf){target="_blank"} (*this is a pdf presentation*)
 - [The Bees](http://www.floridasnativebees.com/the-bees.html){target="_blank"}

## Creating a wildlife habitat:
 - [Garden for Wildlife](https://www.nwf.org/garden-for-wildlife/create){target="_blank"}
 - [Bringing Nature Home](http://www.bringingnaturehome.net/){target="_blank"}
 - [Back 10 Feet](https://thebacktenfeetwithsuescott.com/){target="_blank"}
 - [*In Your Backyard*](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/newsroom/features/?cid=nrcs143_023553){target="_blank"}


## Permaculture and food forests:
 - [ECHO](https://www.echonet.org/take-a-tour){target="_blank"}
 - [The Survival Gardener](http://www.thesurvivalgardener.com/){target="_blank"}
 - [Why food forests](https://permaculturenews.org/2011/10/21/why-food-forests/){target="_blank"}
 - [Gardening Australia](https://www.abc.net.au/gardening/factsheets/permaculture/9423834?fbclid=IwAR3eqLbKIQjoZ3njAc50nfvFbAc92VwvM5TGpklLDi79xXnhXQsRErlHSGI){target="_blank"}


If you find any broken links feel me to [email me](mailto:karatylejulian@gmail.com){target="_blank"} or visit my [Contact Me](https://karatylerjulian.github.io/contactme){target="_blank"} page. 

***

***These links are provided for additional resources to help you transform your garden and motivate you to make a greener world by no means is this a personal endorsement of the organization, authors or publishers. Reference $\neq$ endorsement.***

***